### ISSUE TITLE
Globpatterns and file/path specifications

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/tev2-specifications#9]
There have been discussions by implementers regarding the use of globpatterns and file/path specifications. 

There was an informal consensus to change things in this respect, but that was never documented or fed back to the specifications. 

@Ca5e : do you remember what this is all about, and what needs to be done?

**Comment by Ca5e** [comment]
As of right now, the TRRT CLI expects multiple file path parameters to be set. At least the output and scopedir are required, both of which are converted into so-called 'resolved' paths before being used by the tool (e.g., go from `__tests__/output` to `/home/ubuntu/trrt/__tests__/output`.
Files like the SAF and MRG include paths as well, which are commonly combined with the supplied scopedir to reach a full path.
Changes to this structure should - and will - indeed be updated in the specifications. Some other proposes, like making the `navurl` property of a MRG entry a resolved path or url, may be worth an issue on the MRGT side as well.

Regarding glob patterns.
When using the TRRT inside a terminal, the input files are supplied using a glob pattern *string*, `trrt [ <paramlist> ] [ <globpattern> ]`. *String* in this case, meaning that the pattern is resolved by the tool and not by a (possibly) supporting terminal. When using a config.yaml, multiple patterns may be used using any supporting .yaml format.

An example of a config.yaml that can be used to run the TRRT in its current developmental state `trrt -c __tests__/content/config.yaml`, is shown below.

```yaml
# TRRT configuration file (yaml)
output: __tests__/output
scopedir: __tests__/content
vsntag: latest
interpreter: (?:(?<=[^`\\])|^)\[(?=[^@\]]+\]\([#a-z0-9_-]*@[:a-z0-9_-]*\))(?<showtext>[^\n\]@]+)\]\((?:(?<id>[a-z0-9_-]*)?(?:#(?<trait>[a-z0-9_-]+))?)?@(?<scopetag>[a-z0-9_-]*)(?::(?<vsntag>[a-z0-9_-]+))?\) # `alt` or `default` are also valid
converter: <a href="{{navurl}}{{#trait}}#{{/trait}}{{trait}}" title="{{glossaryText}}">{{showtext}}</a> # `http`, `essif` or `default` are also valid

# glob pattern strings for files to be processed
input:
  - __tests__/content/terminology/*.md
  - ./*.md
  - ./*.html

```
